import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Varela_Round } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import './globals.css';

const varelaRound = Varela_Round({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-varela-round',
});

export const metadata: Metadata = {
  title: "drew's site",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning className={varelaRound.variable}>
      <body className='bg-background'>
        <ThemeProvider attribute='class'>
          <Theme accentColor='indigo' grayColor='sand' radius='large'>
            <Navbar />
            <main className='min-h-screen overflow-x-hidden'>{children}</main>
            <Footer />
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
