import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Roboto_Slab } from 'next/font/google';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import './globals.css';

const font = Roboto_Slab({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: "drew's site",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning className={font.className}>
      <body>
        <ThemeProvider attribute='class'>
          <Navbar />
          <main className='min-h-screen overflow-x-hidden'>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
